"""Handbook entries orders 71–141 (Course 7 – Course 15)."""

from __future__ import annotations

from typing import Any


def entries() -> dict[int, dict[str, Any]]:
    return {
        71: {
            "one_liner": "Hamel evals (Month 7)—deepen golden-set design and error analysis before CI gates.",
            "why_now": "Second Hamel pass; you now have RAG and chunks to label meaningfully.",
            "mental_model": "Error analysis spreadsheet drives what to label next.",
            "beginner_extra": "Re-read golden set + error analysis sections with your failures open.",
            "intermediate_deep_dive": "Bucket failures: retrieval, extraction, generation, policy; label 10 per bucket.",
            "advanced_extra": "Publish labeling guide so future contributors agree on ambiguous cases.",
            "read_sections": ["Golden sets", "Error analysis", "Launch criteria"],
            "failure_modes": ["Single-number accuracy worship"],
            "interview_prompts": ["How do you prioritize labeling budget?"],
            "capstone_action": "ERROR_ANALYSIS.md with buckets and counts.",
            "done_when": "≥30 golden rows committed with guidelines.",
        },
        72: {
            "one_liner": "Applied LLMs evaluation chapters—production testing and monitoring loops.",
            "why_now": "Handbook pass aligning eval harness with staff-level monitoring story.",
            "mental_model": "Eval harness + online monitors = batch + streaming DQ.",
            "beginner_extra": "Read evaluation/monitoring sections.",
            "intermediate_deep_dive": "Map handbook monitoring advice to Langfuse hooks (Month 9).",
            "advanced_extra": "Define canary releases: shadow traffic comparing metrics pre/post prompt change.",
            "read_sections": ["Evaluation", "Monitoring", "Continuous improvement"],
            "failure_modes": ["Offline evals only, no production signals"],
            "interview_prompts": ["Offline vs online eval—what breaks if you only have one?"],
            "capstone_action": "Monitoring checklist in docs/evals.md.",
            "done_when": "Checklist items mapped to future work or implemented.",
        },
        73: {
            "one_liner": "DeepEval getting started—pytest-style LLM evaluations for local and CI runs.",
            "why_now": "Primary library option for automated metrics in Month 7–8.",
            "mental_model": "DeepEval = pytest for model outputs.",
            "beginner_extra": "Install; run hello-world metric on one golden row.",
            "intermediate_deep_dive": "Structure `evals/` package with datasets and thresholds.",
            "advanced_extra": "Cache model calls in CI with recorded fixtures to reduce cost/flake.",
            "read_sections": ["Getting started", "Metrics", "Datasets"],
            "failure_modes": ["Flaky CI calling live APIs without mocks"],
            "interview_prompts": ["How do you keep LLM eval CI deterministic?"],
            "capstone_action": "DeepEval metric on subset of golden set.",
            "done_when": "Local run prints JSON summary.",
        },
        74: {
            "one_liner": "Ragas install docs—framework for RAG-specific metrics (faithfulness, context precision).",
            "why_now": "Complements DeepEval for retrieval-heavy failures.",
            "mental_model": "Ragas = Great Expectations for RAG pipelines.",
            "beginner_extra": "Follow install guide; pin versions in requirements/uv.",
            "intermediate_deep_dive": "Convert golden set to Ragas dataset format.",
            "advanced_extra": "Document when Ragas disagrees with human labels—calibration notes.",
            "read_sections": ["Install", "Quickstart"],
            "failure_modes": ["Running Ragas without reference contexts"],
            "interview_prompts": ["Explain faithfulness vs answer correctness."],
            "capstone_action": "Ragas wired in eval runner optional path.",
            "done_when": "One Ragas metric runs on ≥5 examples.",
        },
        75: {
            "one_liner": "Ragas metrics reference—choose metrics aligned with your failure buckets.",
            "why_now": "Avoid metric soup—pick metrics tied to error analysis.",
            "mental_model": "Each metric = one hypothesis about system quality.",
            "beginner_extra": "Read definitions before enabling all metrics in CI.",
            "intermediate_deep_dive": "Tier 1: schema + retrieval hit; Tier 2: faithfulness; Tier 3: business KPIs.",
            "advanced_extra": "Composite gate with explicit weights documented in ADR.",
            "read_sections": ["Metrics overview", "Faithfulness", "Context precision"],
            "failure_modes": ["10 metrics, none actionable"],
            "interview_prompts": ["Which metric caught your last regression?"],
            "capstone_action": "METRICS.md with tier table.",
            "done_when": "Tiers linked to CI config.",
        },
        76: {
            "one_liner": "Build evals/golden.jsonl and python -m evals.run producing JSON report.",
            "why_now": "Month 7 core—repeatable quality score for every PR touching prompts/retrieval.",
            "mental_model": "evals.run = dbt test for LLM stack.",
            "beginner_extra": "≥30 labeled rows; script exits non-zero on threshold breach.",
            "intermediate_deep_dive": "Report includes per-metric breakdown and worst examples path.",
            "advanced_extra": "Store historical reports in artifacts/ for trend charts.",
            "failure_modes": ["Golden set too easy", "Non-deterministic runs without seeds"],
            "interview_prompts": ["Show eval report from a real PR."],
            "capstone_action": "Merge eval package + sample report in README.",
            "done_when": "`evals.run` documented and working.",
        },
        77: {
            "one_liner": "Prove Month 7: golden set committed plus summary metrics in README or CI artifact.",
            "why_now": "Demonstrates eval culture before blocking merges in Month 8.",
            "mental_model": "Prove = git history shows golden labels + latest scores.",
            "beginner_extra": "Studio link to commit or CI run.",
            "intermediate_deep_dive": "Reviewer reruns evals and compares to published summary.",
            "advanced_extra": "Include worst 3 examples and planned fixes.",
            "failure_modes": ["Metrics screenshot without reproducible command"],
            "interview_prompts": ["How big is your golden set and why?"],
            "capstone_action": "Publish prove evidence.",
            "done_when": "Course 7 acceptance met.",
        },
        78: {
            "one_liner": "Hamel articles index—ongoing essays on evals, product, and LLM ops (Month 8 curated read).",
            "why_now": "Stay current on eval anti-patterns while wiring CI.",
            "mental_model": "Hamel = staff engineer newsletter for LLM quality.",
            "beginner_extra": "Pick 2 articles on CI or error analysis from index.",
            "intermediate_deep_dive": "One article → one change in `.github/workflows/evals.yml`.",
            "advanced_extra": "Subscribe mentally: revisit index when evals feel stale.",
            "read_sections": ["Evals", "CI", "Product"],
            "failure_modes": ["Reading without changing CI"],
            "interview_prompts": ["Recent eval insight you applied?"],
            "capstone_action": "DEVLOG entry citing article + PR.",
            "done_when": "PR references article decision.",
        },
        79: {
            "one_liner": "DeepEval CI/CD guide—run evals on pull requests with thresholds and baselines.",
            "why_now": "Month 8 turns eval harness into merge gate.",
            "mental_model": "baseline.json = golden master for metrics.",
            "beginner_extra": "Follow end-to-end CI doc; start with one metric gate.",
            "intermediate_deep_dive": "Store baseline; fail PR on regression beyond epsilon.",
            "advanced_extra": "Fork PR workflows: smoke on every PR, full eval nightly to control cost.",
            "read_sections": ["CI/CD", "Baseline", "GitHub Actions"],
            "failure_modes": ["CI always calls expensive models", "No baseline update process"],
            "interview_prompts": ["How do you update eval baselines safely?"],
            "capstone_action": "evals.yml with failing test demo branch.",
            "done_when": "CI fails on intentional bad prompt.",
        },
        80: {
            "one_liner": "Applied LLMs testing/monitoring—align handbook with your CI and future Langfuse traces.",
            "why_now": "Connects offline CI to online monitoring story for interviews.",
            "mental_model": "Testing pyramid for LLM apps.",
            "beginner_extra": "Read testing + monitoring sections.",
            "intermediate_deep_dive": "Diagram unit vs eval vs canary in docs.",
            "advanced_extra": "Define alert when online metric diverges from offline eval.",
            "read_sections": ["Testing", "Monitoring"],
            "failure_modes": ["CI green but production quality unknown"],
            "interview_prompts": ["Describe your LLM testing pyramid."],
            "capstone_action": "Testing pyramid diagram committed.",
            "done_when": "Each layer has example in repo.",
        },
        81: {
            "one_liner": "Build .github/workflows/evals.yml and evals/baseline.json for regression detection.",
            "why_now": "Month 8 deliverable—quality gate like dbt tests on PR.",
            "mental_model": "baseline.json = committed expected metric ranges.",
            "beginner_extra": "Workflow runs on PR; uses secrets for API keys in CI only.",
            "intermediate_deep_dive": "Document how to refresh baseline with team review.",
            "advanced_extra": "Comment bot posts metric diff on PR.",
            "failure_modes": ["Skipping CI on docs-only changes that affect prompts"],
            "interview_prompts": ["Show CI blocking a bad change."],
            "capstone_action": "Merge workflow + baseline.",
            "done_when": "Screenshot or link of failed run.",
        },
        82: {
            "one_liner": "Prove Month 8: CI regression screenshot or link showing eval failure on bad prompt.",
            "why_now": "Evidence that gate works—not theoretical YAML.",
            "mental_model": "Failed CI run = trust artifact.",
            "beginner_extra": "Redacted screenshot acceptable.",
            "intermediate_deep_dive": "Include PR link and which metric regressed.",
            "advanced_extra": "Postmortem template for eval regressions.",
            "failure_modes": ["Fake failure without reproducible branch"],
            "interview_prompts": ["Tell story of catching a regression pre-merge."],
            "capstone_action": "Studio prove link.",
            "done_when": "Course 8 acceptance met.",
        },
        83: {
            "one_liner": "LangSmith crash course—tracing chains/agents for debugging (concepts apply to Langfuse path too).",
            "why_now": "Month 9 observability—see inside multi-step runs.",
            "mental_model": "Trace = distributed trace for LLM steps.",
            "beginner_extra": "Watch for span hierarchy and replay debugging.",
            "intermediate_deep_dive": "Map concepts to Langfuse integration you will build.",
            "advanced_extra": "Compare vendor lock-in vs OpenTelemetry export strategy.",
            "watch_for": ["Runs vs traces", "Datasets", "Evaluators in UI"],
            "failure_modes": ["Tracing PII payloads"],
            "interview_prompts": ["Debug a failed agent run using traces."],
            "capstone_action": "TRACE.md glossary of span names you will use.",
            "done_when": "Span naming convention documented.",
        },
        84: {
            "one_liner": "Optional Context Engineering for Agents (~1h)—revisit if Month 9 traces show context bloat.",
            "why_now": "Optional remediation when token/cost traces spike.",
            "mental_model": "Same video as Month 2—new lens with trace data.",
            "beginner_extra": "Only if Langfuse shows oversized tool messages.",
            "intermediate_deep_dive": "Implement one trimming fix; measure token delta.",
            "advanced_extra": "Relate to prompt caching checklist in Month 10.",
            "watch_for": ["Context trimming", "Tool output limits"],
            "failure_modes": ["Re-watching without code change"],
            "interview_prompts": ["Prove context fix with metrics."],
            "capstone_action": "Optional PR reducing tokens/run.",
            "done_when": "Skip if traces already healthy.",
        },
        85: {
            "one_liner": "Open Policy Agent docs—policy-as-code to allow/deny tool and write operations.",
            "why_now": "Month 9 policy layer before agents get write tools in capstone.",
            "mental_model": "Rego policies = row-level security for tools.",
            "beginner_extra": "Read intro + policy language basics.",
            "intermediate_deep_dive": "Policy tests with `opa test` in CI.",
            "advanced_extra": "Separate policy bundle per environment; signed bundles for prod.",
            "read_sections": ["Introduction", "Policy language", "Testing"],
            "failure_modes": ["Policies only in prompts"],
            "interview_prompts": ["OPA vs application-level checks?"],
            "capstone_action": "policies/ folder with README.",
            "done_when": "opa test passes locally.",
        },
        86: {
            "one_liner": "Langfuse docs—LLM observability product overview (traces, scores, datasets).",
            "why_now": "Chosen trace sink for capstone alongside LiteLLM.",
            "mental_model": "Langfuse = DataDog for LLM spans.",
            "beginner_extra": "Skim docs; create project and API keys in dev only.",
            "intermediate_deep_dive": "Define what metadata every trace must include.",
            "advanced_extra": "Data retention and PII scrubbing configuration documented.",
            "read_sections": ["Get started", "Tracing", "Scores"],
            "failure_modes": ["Logging secrets in trace metadata"],
            "interview_prompts": ["What do you store per trace vs per span?"],
            "capstone_action": "Dev Langfuse project wired in config.",
            "done_when": "Test trace appears in UI.",
        },
        87: {
            "one_liner": "Langfuse tracing—instrument LangGraph nodes and LiteLLM calls with consistent run ids.",
            "why_now": "Implementation guide for Month 9 build.",
            "mental_model": "run_id correlates gateway log, graph checkpoint, trace UI.",
            "beginner_extra": "Follow tracing quickstart for Python.",
            "intermediate_deep_dive": "Propagate trace context through MCP tool calls where possible.",
            "advanced_extra": "SLO dashboard: P95 end-to-end agent latency from traces.",
            "read_sections": ["Tracing", "SDK", "Integrations"],
            "failure_modes": ["Broken parent/child span links"],
            "interview_prompts": ["Correlate LiteLLM cost log to Langfuse trace."],
            "capstone_action": "Instrumentation PR with sample trace screenshot.",
            "done_when": "One full run visible end-to-end.",
        },
        88: {
            "one_liner": "OpenTelemetry Python docs—vendor-neutral tracing if you outgrow single SaaS.",
            "why_now": "Understand escape hatch from Langfuse-only instrumentation.",
            "mental_model": "OTel = portable trace IDs across tools.",
            "beginner_extra": "Read concepts: tracer, span, exporter.",
            "intermediate_deep_dive": "Optional: export OTel to Langfuse or collector.",
            "advanced_extra": "Unified observability story for platform interviews.",
            "read_sections": ["Python getting started", "Instrumentation"],
            "failure_modes": ["Double instrumentation overhead unmeasured"],
            "interview_prompts": ["Langfuse vs OTel—when both?"],
            "capstone_action": "Note OTel strategy in OBSERVABILITY.md.",
            "done_when": "Strategy doc committed.",
        },
        89: {
            "one_liner": "LiteLLM Langfuse integration—single hook to log all gateway completions to traces.",
            "why_now": "Wires Month 1 gateway to Month 9 traces with minimal code.",
            "mental_model": "Integration = automatic span per completion.",
            "beginner_extra": "Follow integration doc; verify one completion creates span.",
            "intermediate_deep_dive": "Include custom metadata: job_id, course_tag, model_fallback flag.",
            "advanced_extra": "Cost fields in trace metadata for FinOps dashboards.",
            "read_sections": ["Langfuse integration", "Callbacks"],
            "failure_modes": ["Double logging LiteLLM + manual spans inconsistently"],
            "interview_prompts": ["Show integration config snippet redacted."],
            "capstone_action": "Enable integration in proxy config.",
            "done_when": "Gateway calls appear in Langfuse.",
        },
        90: {
            "one_liner": "Build Rego policy blocking write_* tools for role analyst.",
            "why_now": "Concrete policy proving OPA is not theoretical.",
            "mental_model": "Role → allowed tool name patterns.",
            "beginner_extra": "Start with one deny rule + unit test.",
            "intermediate_deep_dive": "Integrate policy check in MCP server before tool execution.",
            "advanced_extra": "Audit denied attempts separately from allowed.",
            "failure_modes": ["Policy bypass via renamed tools"],
            "interview_prompts": ["Enforce policy at which layer?"],
            "capstone_action": "Policy + test + integration point.",
            "done_when": "Test shows analyst blocked from write tool.",
        },
        91: {
            "one_liner": "Build Langfuse wired to LangGraph + LiteLLM for unified traces.",
            "why_now": "Month 9 integration milestone.",
            "mental_model": "One run_id from CLI through graph, gateway, tools.",
            "beginner_extra": "Follow TRACE.md conventions.",
            "intermediate_deep_dive": "Document env vars and local docker-compose for Langfuse optional.",
            "advanced_extra": "Runbook: trace-driven incident response steps.",
            "failure_modes": ["Traces without cost/token fields"],
            "interview_prompts": ["Demo trace for failed validation path."],
            "capstone_action": "Merge instrumentation.",
            "done_when": "Screenshot with run id in README.",
        },
        92: {
            "one_liner": "Prove Month 9: trace screenshot plus policy test output.",
            "why_now": "Shows observability + authorization together.",
            "mental_model": "Two artifacts: trace UI + opa test stdout.",
            "beginner_extra": "Redact sensitive fields.",
            "intermediate_deep_dive": "Link both to same synthetic scenario.",
            "advanced_extra": "Explain how trace proves policy fired (metadata).",
            "failure_modes": ["Unrelated screenshots"],
            "interview_prompts": ["Security + observability story in 5 min."],
            "capstone_action": "Prove section in README.",
            "done_when": "Course 9 acceptance met.",
        },
        93: {
            "one_liner": "Capstone ingestion: Docling or LlamaParse on public/synthetic docs feeding chunks pipeline.",
            "why_now": "Month 10 integrates prior months into runnable alpha.",
            "mental_model": "Ingestion job = scheduled bronze load.",
            "beginner_extra": "Wire existing Month 5 parser into capstone checklist row.",
            "intermediate_deep_dive": "Idempotent job keyed by doc_id; metrics on parse failures.",
            "advanced_extra": "Backpressure and retry policy on parse queue.",
            "failure_modes": ["Manual one-off parses only"],
            "interview_prompts": ["End-to-end data flow from PDF to answer."],
            "capstone_action": "Checklist row done with command in README.",
            "done_when": "Ingest command documented.",
        },
        94: {
            "one_liner": "Capstone gateway: LiteLLM proxy + failover + prompt caching on static prefixes.",
            "why_now": "Production-shaped inference path for integrated demo.",
            "mental_model": "Caching = reuse compiled prefix tokens for schemas/tools.",
            "beginner_extra": "Enable caching per practical gate readings later in course.",
            "intermediate_deep_dive": "Measure TTFT and cached token fields in logs.",
            "advanced_extra": "Cache invalidation when tool schema version changes.",
            "failure_modes": ["Caching stale tool definitions"],
            "interview_prompts": ["Explain prompt caching cost win with numbers."],
            "capstone_action": "Gateway row checked with caching config.",
            "done_when": "Logs show cache hits on repeated prefix.",
        },
        95: {
            "one_liner": "Capstone extraction: Instructor + Pydantic + validation retries on integrated path.",
            "why_now": "Core business logic in alpha pipeline.",
            "mental_model": "Extract step = typed transform in DAG.",
            "beginner_extra": "Reuse boot-week module; no duplicate extract code.",
            "intermediate_deep_dive": "Single entrypoint function called from graph node.",
            "advanced_extra": "Circuit breaker when validation error rate spikes.",
            "failure_modes": ["Different extract behavior in CLI vs graph"],
            "interview_prompts": ["Where is schema enforced?"],
            "capstone_action": "Integration test on extract node.",
            "done_when": "Test passes in CI.",
        },
        96: {
            "one_liner": "Capstone invariants & lineage: root validators; chunk → model → output lineage fields.",
            "why_now": "Auditability for integrated answers.",
            "mental_model": "Lineage fields on output: chunk_ids, model, prompt_hash.",
            "beginner_extra": "Add fields to output JSON schema.",
            "intermediate_deep_dive": "OpenLineage event preview for one run (Month 12 expands).",
            "advanced_extra": "Immutable lineage log for compliance narrative.",
            "failure_modes": ["Lineage optional/null in prod path"],
            "interview_prompts": ["Trace an answer back to source chunks."],
            "capstone_action": "Lineage fields populated in demo run.",
            "done_when": "Sample output JSON shows lineage.",
        },
        97: {
            "one_liner": "Capstone policy: OPA before write tools in integrated agent path.",
            "why_now": "Safety gate in end-to-end demo.",
            "mental_model": "Policy check = mandatory middleware on tool router.",
            "beginner_extra": "Reuse Month 9 policies.",
            "intermediate_deep_dive": "Deny path surfaces user-safe error + audit log.",
            "advanced_extra": "Policy version in trace metadata.",
            "failure_modes": ["Write tools callable in alpha demo without policy"],
            "interview_prompts": ["Demo policy deny in integrated run."],
            "capstone_action": "Policy wired in capstone graph.",
            "done_when": "Deny scenario tested.",
        },
        98: {
            "one_liner": "Capstone LangGraph: pass → stage write; fail → interrupt() HITL in integrated flow.",
            "why_now": "Human gate on bad extractions in alpha story.",
            "mental_model": "Same HITL as Month 2, now in full pipeline.",
            "beginner_extra": "Document operator steps in DEMO.md.",
            "intermediate_deep_dive": "Resume path tested after human correction.",
            "advanced_extra": "Metrics on interrupt rate and time-to-resume.",
            "failure_modes": ["HITL bypassed in ‘happy path only’ demo"],
            "interview_prompts": ["Walk alpha demo including interrupt."],
            "capstone_action": "DEMO.md script includes fail branch.",
            "done_when": "Demo script rehearsed.",
        },
        99: {
            "one_liner": "Capstone eval CI: GitHub Actions + tiered metrics on integrated golden set.",
            "why_now": "Quality gate on whole pipeline, not isolated scripts.",
            "mental_model": "CI runs end-to-end or staged eval on golden.jsonl.",
            "beginner_extra": "Reuse Month 8 workflow; expand dataset.",
            "intermediate_deep_dive": "Tiered thresholds documented in METRICS.md.",
            "advanced_extra": "Nightly full eval vs PR smoke documented.",
            "failure_modes": ["CI tests mock only, alpha untested"],
            "interview_prompts": ["What blocks alpha tag merge?"],
            "capstone_action": "CI green on main with eval summary.",
            "done_when": "Workflow linked in README.",
        },
        100: {
            "one_liner": "Capstone telemetry: Langfuse or OTel trace per integrated run.",
            "why_now": "Demo credibility—show observability in alpha.",
            "mental_model": "Every demo run has shareable trace id.",
            "beginner_extra": "Screenshot in DEMO.md.",
            "intermediate_deep_dive": "Spans for ingest, retrieve, extract, validate, respond.",
            "advanced_extra": "Alerting sketch on error rate (even if not wired).",
            "failure_modes": ["Demo without trace id"],
            "interview_prompts": ["Open trace and explain spans live."],
            "capstone_action": "Telemetry row checked.",
            "done_when": "Trace id in demo script.",
        },
        101: {
            "one_liner": "Optional Phase 5: E2B, semantic cache, NeMo—document defer/adopt with metrics.",
            "why_now": "Frontier extras only after alpha required rows done.",
            "mental_model": "Optional row = ADR + spike, not scope creep.",
            "beginner_extra": "Skip unless alpha prove complete.",
            "intermediate_deep_dive": "If explored, README section with bottleneck + metric.",
            "advanced_extra": "Honest ‘deferred’ entries valued in staff interviews.",
            "failure_modes": ["Optional features blocking alpha"],
            "interview_prompts": ["What did you consciously defer?"],
            "capstone_action": "DEFERRED.md or README section.",
            "done_when": "Alpha required items done first.",
        },
        102: {
            "one_liner": "Practical gate: identify static prefix (schemas, tools, policy, few-shots) for caching.",
            "why_now": "Cost/latency optimization with measurable evidence.",
            "mental_model": "Static prefix = stable system prompt blocks.",
            "beginner_extra": "List prefix components in CACHING.md.",
            "intermediate_deep_dive": "Separate volatile user content from stable prefix in code.",
            "advanced_extra": "Version prefix hash when schemas change.",
            "failure_modes": ["Caching entire prompt including user PII"],
            "interview_prompts": ["What is safe to cache?"],
            "capstone_action": "CACHING.md committed.",
            "done_when": "Prefix list reviewed.",
        },
        103: {
            "one_liner": "Anthropic prompt caching docs—provider-native cache breakpoints and billing.",
            "why_now": "Understand cache read/write pricing for interview numbers.",
            "mental_model": "Cache breakpoints mark reusable prefix sections.",
            "beginner_extra": "Read how to mark cacheable blocks in API calls.",
            "intermediate_deep_dive": "Implement if using Anthropic models; else document N/A with LiteLLM path.",
            "advanced_extra": "Compare Anthropic vs LiteLLM caching abstractions.",
            "read_sections": ["Prompt caching", "Pricing implications"],
            "failure_modes": ["Assuming cache hits without log verification"],
            "interview_prompts": ["Explain cache read vs write tokens."],
            "capstone_action": "Config snippet or N/A note.",
            "done_when": "README references provider caching behavior.",
        },
        104: {
            "one_liner": "LiteLLM prompt caching—unified caching config across providers where supported.",
            "why_now": "Matches gateway-centric capstone architecture.",
            "mental_model": "LiteLLM passes cache directives to providers.",
            "beginner_extra": "Follow LiteLLM prompt caching doc.",
            "intermediate_deep_dive": "Log cached vs uncached token fields per request.",
            "advanced_extra": "Alert if cache hit rate drops after deploy.",
            "read_sections": ["Prompt caching", "Logging cache stats"],
            "failure_modes": ["Caching without measuring TTFT improvement"],
            "interview_prompts": ["Show ≥10 request table cached vs uncached."],
            "capstone_action": "Caching enabled in proxy.",
            "done_when": "Table in README practical gate.",
        },
        105: {
            "one_liner": "Practical gate README table: TTFT + cached vs uncached tokens over ≥10 requests.",
            "why_now": "Numeric prove for caching work.",
            "mental_model": "Before/after table like query optimization proof.",
            "beginner_extra": "Run scripted load against stable prefix.",
            "intermediate_deep_dive": "Include median and P95 TTFT.",
            "advanced_extra": "Note model/provider and date; reproducible script.",
            "failure_modes": ["Single request cherry-pick"],
            "interview_prompts": ["Quantify caching benefit in one sentence."],
            "capstone_action": "Table committed.",
            "done_when": "Practical gate satisfied.",
        },
        106: {
            "one_liner": "Practical gate: one-sentence interview line on cost/latency without behavior change.",
            "why_now": "Forces crisp communication of optimization.",
            "mental_model": "Elevator pitch backed by table in previous topic.",
            "beginner_extra": "Write sentence in README CACHING.md header.",
            "intermediate_deep_dive": "Peer review: sentence matches table numbers.",
            "advanced_extra": "Practice aloud for Month 15 interviews.",
            "failure_modes": ["Vague ‘caching made it faster’"],
            "interview_prompts": ["Deliver the one-liner live."],
            "capstone_action": "Sentence in README.",
            "done_when": "Numbers align with table.",
        },
        107: {
            "one_liner": "AI Agents in LangGraph (Course 10 repeat)—refresh for integrated capstone graph patterns.",
            "why_now": "Second pass while wiring alpha; focus integration gaps only.",
            "mental_model": "Re-watch targeted modules, not full course.",
            "beginner_extra": "Skip if graph already meets capstone checklist.",
            "intermediate_deep_dive": "Note one pattern fixed after re-watch.",
            "advanced_extra": "Compare DL.AI labs to your production graph structure.",
            "watch_for": ["Multi-node error handling", "Persistence in long runs"],
            "failure_modes": ["Re-taking entire course under deadline"],
            "interview_prompts": ["What changed in graph after Month 10?"],
            "capstone_action": "Optional DEVLOG.",
            "done_when": "Capstone rows drive priority.",
        },
        108: {
            "one_liner": "OpenAPI 3 spec—document HTTP APIs on your platform for integrators.",
            "why_now": "Month 10 integration includes service boundaries.",
            "mental_model": "OpenAPI = contract for non-MCP clients.",
            "beginner_extra": "Skim spec structure; generate or hand-write for one endpoint.",
            "intermediate_deep_dive": "Publish openapi.yaml for reconciler API.",
            "advanced_extra": "Contract tests validating responses against spec.",
            "read_sections": ["Structure", "Paths", "Schemas"],
            "failure_modes": ["Undocumented HTTP endpoints"],
            "interview_prompts": ["How do OpenAPI and MCP relate in your platform?"],
            "capstone_action": "openapi.yaml in repo.",
            "done_when": "Spec validates in CI or lint tool.",
        },
        109: {
            "one_liner": "JSON Schema (Course 10)—align HTTP/MCP/tool contracts with one schema source.",
            "why_now": "Second pass emphasizing single source of truth across surfaces.",
            "mental_model": "Generate Pydantic from schema or vice versa—pick one direction.",
            "beginner_extra": "Ensure tool schemas match OpenAPI components.",
            "intermediate_deep_dive": "CI check for schema drift between MCP and OpenAPI.",
            "advanced_extra": "Breaking change policy for schema versions.",
            "read_sections": ["$ref", "Versioning patterns"],
            "failure_modes": ["Three divergent schema copies"],
            "interview_prompts": ["Schema governance in monorepo?"],
            "capstone_action": "Drift check or shared schema package.",
            "done_when": "Single source documented.",
        },
        110: {
            "one_liner": "Instructor (Course 10)—ensure integrated extract path matches latest patterns.",
            "why_now": "Refresh retries/validators after months of changes.",
            "mental_model": "Regression test protects extract module during capstone merges.",
            "beginner_extra": "Re-read retries if flake increased.",
            "intermediate_deep_dive": "Align with eval CI failures—fix taxonomy.",
            "advanced_extra": "Deprecate legacy extract code paths.",
            "read_sections": ["Retries", "Migration guides"],
            "failure_modes": ["Two extract implementations in alpha"],
            "interview_prompts": ["How do you prevent extract regressions?"],
            "capstone_action": "Consolidate extract entrypoint.",
            "done_when": "One path used in alpha demo.",
        },
        111: {
            "one_liner": "Build integrated pipeline: ingest → gateway (caching) → extract → validate → LangGraph → respond.",
            "why_now": "Month 10 alpha wiring milestone.",
            "mental_model": "Single command runs end-to-end demo.",
            "beginner_extra": "Makefile target `make alpha-demo`.",
            "intermediate_deep_dive": "README 5-minute demo script with prerequisites.",
            "advanced_extra": "Feature flags for optional subsystems.",
            "failure_modes": ["Works only via manual step sequence"],
            "interview_prompts": ["Run alpha demo cold start."],
            "capstone_action": "Merge integration PR.",
            "done_when": "Demo command succeeds on clean clone.",
        },
        112: {
            "one_liner": "Prove Month 10: alpha tag + 5-minute demo script + caching section.",
            "why_now": "Major portfolio milestone.",
            "mental_model": "Git tag alpha = release artifact for recruiters.",
            "beginner_extra": "Tag and push; link in studio.",
            "intermediate_deep_dive": "Demo script timed; includes trace id and eval summary.",
            "advanced_extra": "Record demo video optional for portfolio.",
            "failure_modes": ["Tag without reproducible demo"],
            "interview_prompts": ["Deliver alpha demo in interview."],
            "capstone_action": "Publish alpha + DEMO.md.",
            "done_when": "Course 10 acceptance met.",
        },
        113: {
            "one_liner": "Kubernetes Community channel—deploy concepts for Month 11 (optional video background).",
            "why_now": "Orientation before K8s docs if new to kube.",
            "mental_model": "Pods, services, deployments vocabulary.",
            "beginner_extra": "One intro video if kube is new.",
            "intermediate_deep_dive": "Glossary note in DEPLOY.md.",
            "advanced_extra": (
                "Skip deep kube study if your prove path is compose-only—but still document **why** in DEPLOY.md. "
                "If you use Kubernetes, note how LLM gateway pods differ from stateless APIs: readiness waits for "
                "proxy health, memory limits reflect sidecars, and rollouts need surge strategy so LiteLLM does not "
                "drop in-flight streams. Interview story: smallest deploy surface that satisfies the Course 11 rubric."
            ),
            "watch_for": ["Deployments", "Health checks"],
            "failure_modes": ["Learning K8s instead of shipping chart"],
            "interview_prompts": ["Why Helm for your capstone?"],
            "capstone_action": "DEPLOY.md target environment stated.",
            "done_when": "Deploy path chosen.",
        },
        114: {
            "one_liner": "Kubernetes Deployments docs—replicas, rollouts, probes for agent/gateway services.",
            "why_now": "Month 11 deploy month core reference.",
            "mental_model": "Deployment = managed replica set with rollout strategy.",
            "beginner_extra": "Read deployments + probes sections.",
            "intermediate_deep_dive": "Liveness vs readiness for LLM worker (readiness waits for model warm-up).",
            "advanced_extra": "Rollout analysis: maxUnavailable, surge during gateway upgrades.",
            "read_sections": ["Deployments", "Probes", "Resource management"],
            "failure_modes": ["No readiness probe on slow-start LiteLLM"],
            "interview_prompts": ["Design probes for LLM gateway pod."],
            "capstone_action": "deployment.yaml sketch.",
            "done_when": "Probes defined in manifest.",
        },
        115: {
            "one_liner": "Helm quickstart—package Kubernetes manifests for reproducible installs.",
            "why_now": "Capstone deliverable often Helm or compose—Helm for kube path.",
            "mental_model": "Helm chart = parameterized Terraform for k8s apps.",
            "beginner_extra": "helm install your chart on kind/minikube.",
            "intermediate_deep_dive": "Values for secrets, image tags, resource limits.",
            "advanced_extra": "Chart versioning aligned with git tags.",
            "read_sections": ["Quickstart", "Charts", "Values"],
            "failure_modes": ["Secrets in values.yaml committed"],
            "interview_prompts": ["What goes in values vs templates?"],
            "capstone_action": "chart/ directory with README.",
            "done_when": "helm template renders cleanly.",
        },
        116: {
            "one_liner": "Argo CD getting started—GitOps deploy pattern for platform teams.",
            "why_now": "Optional but strong interview story for deploy month.",
            "mental_model": "Argo syncs cluster from git—desired state deployments.",
            "beginner_extra": "Skim concepts; adopt only if using k8s prove path.",
            "intermediate_deep_dive": "Document git → cluster flow in DEPLOY.md.",
            "advanced_extra": "Promotion across dev/stage via branches.",
            "read_sections": ["Getting started", "Sync policies"],
            "failure_modes": ["Argo scope creep without running app"],
            "interview_prompts": ["GitOps vs kubectl apply in CI?"],
            "capstone_action": "Optional Argo app manifest.",
            "done_when": "Deploy docs complete without Argo if compose-only.",
        },
        117: {
            "one_liner": "LiteLLM proxy server docs—deploy gateway as standalone service in chart.",
            "why_now": "Gateway is first-class deployable in Month 11.",
            "mental_model": "LiteLLM deployment = shared platform service.",
            "beginner_extra": "Follow proxy server guide for docker/k8s.",
            "intermediate_deep_dive": "Horizontal scaling notes; sticky sessions if needed.",
            "advanced_extra": "Budgets and rate limits per API key in multi-user sketch.",
            "read_sections": ["Proxy server", "Deploy", "Config"],
            "failure_modes": ["Embedding gateway in every worker pod"],
            "interview_prompts": ["Scale LiteLLM proxy—what breaks first?"],
            "capstone_action": "Gateway service in chart/compose.",
            "done_when": "Health endpoint responds in deploy env.",
        },
        118: {
            "one_liner": "Build Helm chart or docker-compose for runnable deploy of capstone stack.",
            "why_now": "Month 11 prove artifact.",
            "mental_model": "Another engineer clones and brings stack up.",
            "beginner_extra": "Choose compose OR helm; document prerequisites.",
            "intermediate_deep_dive": "ADD_TOOL.md for registering a new MCP tool.",
            "advanced_extra": (
                "Resource requests should cite a **load test note**: concurrent extract jobs, gateway RPS, and MCP "
                "latency. Document secrets via env vars or external secret store—never commit values. Split stateless "
                "workers from gateway/proxy so you scale extraction without duplicating routing config. Add a smoke "
                "test in CI that hits /health and one golden extract against a stub model if live APIs are too flaky."
            ),
            "failure_modes": ["Undocumented env vars"],
            "interview_prompts": ["Onboard a teammate using your deploy docs."],
            "capstone_action": "Merge deploy artifacts.",
            "done_when": "DEPLOY.md steps verified.",
        },
        119: {
            "one_liner": "Prove Month 11: kubectl get pods or compose screenshot + adding-a-tool doc.",
            "why_now": "Deploy evidence for portfolio.",
            "mental_model": "Screenshot + doc = prove.",
            "beginner_extra": "Redact cluster names if needed.",
            "intermediate_deep_dive": "Second person follows doc successfully.",
            "advanced_extra": "SLO note for uptime of demo env.",
            "failure_modes": ["Works only on your machine"],
            "interview_prompts": ["How would you hand off deploy to SRE?"],
            "capstone_action": "Prove link.",
            "done_when": "Course 11 acceptance met.",
        },
        120: {
            "one_liner": "OpenLineage project overview—standard for job/run/dataset lineage events.",
            "why_now": "Month 12 lineage narrative for LLM outputs.",
            "mental_model": "Lineage event = who ran what on which dataset producing which output.",
            "beginner_extra": "Watch/read intro; understand Job/Run/Dataset facets.",
            "intermediate_deep_dive": "Map facets to your chunk → model → answer path.",
            "advanced_extra": "Integrate with existing data platform lineage if applicable.",
            "watch_for": ["Event model", "Integrations"],
            "failure_modes": ["Lineage as afterthought JSON dump"],
            "interview_prompts": ["Emit one OpenLineage event—explain fields."],
            "capstone_action": "LINEAGE.md mapping table.",
            "done_when": "Mapping committed.",
        },
        121: {
            "one_liner": "OpenLineage documentation—JSON spec for emitting lineage from your pipeline.",
            "why_now": "Implement sample artifact for v1.0 prove.",
            "mental_model": "lineage.json = test fixture for lineage emitter.",
            "beginner_extra": "Follow Python or JSON examples in docs.",
            "intermediate_deep_dive": "Emit event on successful alpha run (script hook).",
            "advanced_extra": "Validate event against JSON schema in CI.",
            "read_sections": ["Spec", "Python client", "Facets"],
            "failure_modes": ["Invalid facet names"],
            "interview_prompts": ["Lineage for RAG vs batch ETL—similarities?"],
            "capstone_action": "sample_lineage.json committed.",
            "done_when": "CI validates JSON.",
        },
        122: {
            "one_liner": "Applied LLMs production pitfalls—hardening checklist before v1.0 tag.",
            "why_now": "Final handbook pass for reliability and security themes.",
            "mental_model": "Pre-v1.0 review against handbook pitfall list.",
            "beginner_extra": "Read pitfalls/failure sections.",
            "intermediate_deep_dive": "Tick checklist; file issues for gaps.",
            "advanced_extra": "Threat model summary in SECURITY.md.",
            "read_sections": ["Pitfalls", "Security", "Operations"],
            "failure_modes": ["Shipping v1.0 with known open pitfall"],
            "interview_prompts": ["Top pitfall you mitigated in v1.0?"],
            "capstone_action": "HARDENING.md checklist.",
            "done_when": "Critical items addressed or documented.",
        },
        123: {
            "one_liner": "Build sample lineage JSON emitted from pipeline run.",
            "why_now": "Month 12 build integration.",
            "mental_model": "Emitter function called at end of alpha-demo.",
            "beginner_extra": "One static sample acceptable for prove; dynamic emitter better.",
            "intermediate_deep_dive": "Include input dataset URIs (chunk manifest) and output URI.",
            "advanced_extra": "Link lineage run id to Langfuse trace id.",
            "failure_modes": ["Lineage disconnected from real run"],
            "interview_prompts": ["Walk through lineage JSON field by field."],
            "capstone_action": "Emitter merged.",
            "done_when": "Demo produces lineage file.",
        },
        124: {
            "one_liner": "Prove Month 12: v1.0 tag + lineage artifact.",
            "why_now": "Year-one capstone completion signal.",
            "mental_model": "v1.0 = hardened release with lineage story.",
            "beginner_extra": "Tag v1.0; link lineage sample in README.",
            "intermediate_deep_dive": "Release notes summarize year capabilities.",
            "advanced_extra": (
                "v1.0 is a **narrative release**: notes should list eval CI gates, policy tests, deploy path, and "
                "lineage sample. Include migration notes from alpha → v1.0 (schema changes, new env vars). Tie "
                "lineage JSON to Langfuse run_id where possible. File explicit DEFERRED.md items with risk owner for "
                "anything not shipped."
            ),
            "failure_modes": ["v1.0 without reproducible lineage"],
            "interview_prompts": ["Tell v1.0 story with lineage and evals."],
            "capstone_action": "Publish v1.0 prove.",
            "done_when": "Course 12 acceptance met.",
        },
        125: {
            "one_liner": "Frontier vLLM—local high-throughput inference behind LiteLLM (pick-one track).",
            "why_now": "Month 13 depth: measure before/after for one bottleneck.",
            "mental_model": "vLLM = self-hosted inference service.",
            "beginner_extra": "Read docs overview; spike only if GPU available or use small model.",
            "intermediate_deep_dive": "LiteLLM routes subset of traffic to vLLM; compare latency/cost.",
            "advanced_extra": "Ops burden ADR: when self-host beats API.",
            "read_sections": ["Getting started", "Deployment"],
            "failure_modes": ["Self-host without eval comparison"],
            "interview_prompts": ["When would you operate vLLM in prod?"],
            "capstone_action": "FRONTIER.md metric story.",
            "done_when": "One frontier track chosen and measured.",
        },
        126: {
            "one_liner": "Frontier DSPy—compiled prompts/programs with metric-driven optimization.",
            "why_now": "Alternative frontier track for extraction quality plateaus.",
            "mental_model": "DSPy = AutoML for prompt modules with eval metric.",
            "beginner_extra": "Run one tutorial metric on golden subset.",
            "intermediate_deep_dive": "Compare DSPy compiled program vs Instructor baseline.",
            "advanced_extra": "Cost of compilation runs; CI strategy for compiled artifacts.",
            "read_sections": ["Intro", "Teleprompters", "Metrics"],
            "failure_modes": ["Optimizing on tiny set overfitting"],
            "interview_prompts": ["DSPy vs manual prompt engineering?"],
            "capstone_action": "Benchmark note in FRONTIER.md.",
            "done_when": "Metric comparison documented.",
        },
        127: {
            "one_liner": "Frontier Anthropic prefix caching—TTFT before/after at provider level.",
            "why_now": "Frontier track if caching not fully explored in Month 10.",
            "mental_model": "Deep dive on provider cache metrics.",
            "beginner_extra": "Extend Month 10 table with provider-specific detail.",
            "intermediate_deep_dive": "10+ requests with cache breakpoints tuned.",
            "advanced_extra": "Document when provider cache invalidates.",
            "read_sections": ["Prompt caching"],
            "failure_modes": ["Duplicate work from Month 10 without new insight"],
            "interview_prompts": ["Quantify TTFT improvement again with nuance."],
            "capstone_action": "Update CACHING.md with frontier notes.",
            "done_when": "New insight or explicit N/A.",
        },
        128: {
            "one_liner": "Frontier GPTCache—semantic cache layer optional at gateway.",
            "why_now": "Explore response caching for repeated similar queries.",
            "mental_model": "Semantic cache = approximate dedup of LLM responses.",
            "beginner_extra": "Read architecture; spike if high duplicate query rate in demo.",
            "intermediate_deep_dive": "Measure hit rate on synthetic repeated questions.",
            "advanced_extra": "Stale answer risk—TTL and invalidation policy.",
            "read_sections": ["README", "Integration"],
            "failure_modes": ["Caching wrong answers semantically similar"],
            "interview_prompts": ["Semantic cache vs prompt cache?"],
            "capstone_action": "FRONTIER.md section on semantic cache.",
            "done_when": "Adopt/defer with metric.",
        },
        129: {
            "one_liner": "Prove Month 13: README frontier section with bottleneck + metric.",
            "why_now": "Shows deliberate depth beyond v1.0.",
            "mental_model": "One measured optimization story.",
            "beginner_extra": "Link FRONTIER.md in prove.",
            "intermediate_deep_dive": "Include before/after table and decision.",
            "advanced_extra": (
                "Frontier prove must show **before/after** on one bottleneck from traces (latency, cost, or eval "
                "score). Link README to Langfuse/LiteLLM evidence. State adopt vs defer with a re-evaluation date. "
                "A documented failed experiment beats a successful spike with no numbers."
            ),
            "failure_modes": ["Frontier without numbers"],
            "interview_prompts": ["Explain your frontier experiment crisply."],
            "capstone_action": "Publish prove.",
            "done_when": "Course 13 acceptance met.",
        },
        130: {
            "one_liner": "Syllabus Unsloth—efficient fine-tuning tooling (portfolio month optional read).",
            "why_now": "Month 14 awareness of fine-tune path when evals justify it.",
            "mental_model": "Unsloth = faster LoRA training experiments.",
            "beginner_extra": "Skim README; no training required for prove.",
            "intermediate_deep_dive": "Note when you would choose fine-tune vs RAG vs prompt.",
            "advanced_extra": "Data governance for fine-tune datasets.",
            "read_sections": ["README", "Quickstart"],
            "failure_modes": ["Fine-tuning without baseline eval"],
            "interview_prompts": ["When is fine-tune worth it?"],
            "capstone_action": "Portfolio post outline mentioning train vs prompt decision.",
            "done_when": "Outline references honest scope.",
        },
        131: {
            "one_liner": "NeMo Guardrails—safety/policy rails around conversations and tools.",
            "why_now": "Complement OPA with model-output guardrails narrative.",
            "mental_model": "Guardrails = configurable safety flows.",
            "beginner_extra": "Read concepts; compare to your OPA layer.",
            "intermediate_deep_dive": "Document overlap: OPA for tools, guardrails for text.",
            "advanced_extra": "When to use both vs policy-only.",
            "read_sections": ["Introduction", "Rails"],
            "failure_modes": ["Duplicate policy in three places uncoordinated"],
            "interview_prompts": ["Layered safety story for your platform."],
            "capstone_action": "SAFETY.md layered diagram.",
            "done_when": "Diagram committed.",
        },
        132: {
            "one_liner": "E2B docs—sandboxed code execution for tool-using agents.",
            "why_now": "Portfolio awareness of execution environments.",
            "mental_model": "E2B = isolated VM for untrusted code tools.",
            "beginner_extra": "Skim docs; optional spike only.",
            "intermediate_deep_dive": "If agents run code, document why not bare subprocess.",
            "advanced_extra": (
                "If agents execute code, compare **E2B (or similar)** vs host subprocess on network egress, secret "
                "exposure, CPU/memory caps, audit logs, and $/minute. Document default-deny egress; sandbox does not "
                "replace OPA/tool authorization. Treat sandboxes like ephemeral Spark executors with strict IAM."
            ),
            "read_sections": ["Sandbox", "SDK"],
            "failure_modes": ["Arbitrary code execution on host"],
            "interview_prompts": ["Secure code execution design?"],
            "capstone_action": "Note in SAFETY or DEFERRED.",
            "done_when": "Position documented.",
        },
        133: {
            "one_liner": "Optional Karpathy Zero to Hero playlist—deep ML foundations for portfolio curiosity.",
            "why_now": "Optional; not required for AI engineer track prove.",
            "mental_model": "Training intuition for conversations with ML engineers.",
            "beginner_extra": "Only if interviewing at training-heavy teams.",
            "intermediate_deep_dive": "One playlist episode tied to blog post if writing.",
            "advanced_extra": "Do not delay portfolio posts for this playlist.",
            "watch_for": ["Backprop intuition", "Architectures"],
            "failure_modes": ["Zero to Hero instead of shipping posts"],
            "interview_prompts": ["How much training math do you need for your role target?"],
            "capstone_action": "Optional learning log.",
            "done_when": "Portfolio prove independent.",
        },
        134: {
            "one_liner": "Prove Month 14: public posts + resume refresh per Master Plan §14.",
            "why_now": "Career artifact month—make work visible.",
            "mental_model": "Post = tutorial with numbers from your repo.",
            "beginner_extra": "One technical post with trace/eval screenshot.",
            "intermediate_deep_dive": "Resume bullets with metrics (valid %, latency, cost).",
            "advanced_extra": "Cross-link GitHub releases in post.",
            "failure_modes": ["Vague resume bullets without numbers"],
            "interview_prompts": ["Walk through your best post."],
            "capstone_action": "Links in prove (public).",
            "done_when": "Course 14 acceptance met.",
        },
        135: {
            "one_liner": "AI Engineer conference talks—curated industry stories for interview narratives.",
            "why_now": "Month 15—learn how seniors present shipping stories.",
            "mental_model": "Talks = templates for your capstone story arc.",
            "beginner_extra": "Watch 2 talks aligned with your repo themes (evals, agents, RAG).",
            "intermediate_deep_dive": "Outline your talk: problem, architecture, metrics, failures.",
            "advanced_extra": "Practice 10-minute version with trace demo.",
            "watch_for": ["Architecture slides", "Lessons learned", "Metrics"],
            "failure_modes": ["Watching talks without practicing your story"],
            "interview_prompts": ["Deliver your capstone as a conference talk outline."],
            "capstone_action": "INTERVIEW_STORY.md outline.",
            "done_when": "Outline has metrics and failure anecdote.",
        },
        136: {
            "one_liner": "Applied LLMs (Month 15)—final read for staff-level vocabulary refresh.",
            "why_now": "Interview month synthesis across handbook.",
            "mental_model": "Skim index; deep-read weak areas flagged in mocks.",
            "beginner_extra": "Pick 3 sections you could not explain well in mock.",
            "intermediate_deep_dive": "Update INTERVIEW_STORY.md with handbook terms used correctly.",
            "advanced_extra": "Prepare ‘what I would do differently v2’ section.",
            "read_sections": ["Index-driven weak spots"],
            "failure_modes": ["Passive re-read without mock feedback"],
            "interview_prompts": ["Staff-level tradeoff question practice."],
            "capstone_action": "Story doc updated.",
            "done_when": "Mock gaps addressed in notes.",
        },
        137: {
            "one_liner": "Anthropic agents essay (Month 15)—refresh workflow vs agent framing for interviews.",
            "why_now": "Common interview topic; tie to your LangGraph design.",
            "mental_model": "Essay bullets = answer scaffold.",
            "beginner_extra": "Re-read workflows vs agents section.",
            "intermediate_deep_dive": "Map essay to your repo: where workflow ends and agent begins.",
            "advanced_extra": "Counterfactual: what if you over-agentified—how evals caught it.",
            "read_sections": ["Workflows vs agents", "Evaluations"],
            "failure_modes": ["Generic essay recap without repo tie-in"],
            "interview_prompts": ["Answer ‘how do you build agents?’ with your project."],
            "capstone_action": "Practice answer recorded or written.",
            "done_when": "Answer references your prove artifacts.",
        },
        138: {
            "one_liner": "Master Plan §14–§15—resume, narrative, and positioning for AI platform roles.",
            "why_now": "Aligns story with what hiring managers scan for.",
            "mental_model": "Resume = index to GitHub evidence.",
            "beginner_extra": "Read positioning sections in master plan doc.",
            "intermediate_deep_dive": "Each bullet points to tag (v1.0, alpha) and metric.",
            "advanced_extra": "Tailor variants for data platform vs ML platform roles.",
            "read_sections": ["Resume", "Narrative", "Positioning"],
            "failure_modes": ["Buzzwords without repo links"],
            "interview_prompts": ["Why AI platform vs data engineer title?"],
            "capstone_action": "Resume diff committed privately or checklist.",
            "done_when": "Positioning statement written.",
        },
        139: {
            "one_liner": "Do: 3–5 quality applications per week with tailored story.",
            "why_now": "Execution habit for job search month.",
            "mental_model": "Applications = targeted loops with custom paragraph.",
            "beginner_extra": "Track in spreadsheet: company, role, story angle, date.",
            "intermediate_deep_dive": "Each application cites one repo metric and one failure learned.",
            "advanced_extra": "A/B test story openings; note response rates privately.",
            "failure_modes": ["Spray and pray resumes"],
            "interview_prompts": ["How do you tailor without lying?"],
            "capstone_action": "Weekly log (private OK).",
            "done_when": "Habit sustained per syllabus.",
        },
        140: {
            "one_liner": "Do: mock system design—orchestration control plane for LLM platform.",
            "why_now": "Practice whiteboard using your capstone as reference implementation.",
            "mental_model": "Mock = design gateway, evals, policy, deploy—your repo is cheat sheet.",
            "beginner_extra": "One mock with peer or rubric self-score.",
            "intermediate_deep_dive": "Timed 45-minute session; capture gaps in INTERVIEW_STORY.md.",
            "advanced_extra": "Second mock focusing on failure modes and scaling.",
            "failure_modes": ["Mocks on trivia not systems"],
            "interview_prompts": ["Whiteboard your architecture without slides."],
            "capstone_action": "Mock notes file updated.",
            "done_when": "At least one mock completed.",
        },
        141: {
            "one_liner": "Prove Month 15: offer or structured interview feedback notes (private OK).",
            "why_now": "Closes loop on job search month.",
            "mental_model": "Feedback notes = retro for story improvements.",
            "beginner_extra": "Save debrief bullets after each onsite.",
            "intermediate_deep_dive": "Update INTERVIEW_STORY.md from feedback patterns.",
            "advanced_extra": "Share anonymized lessons in portfolio if appropriate.",
            "failure_modes": ["No written debrief after rejections"],
            "interview_prompts": ["What question stumped you—how did you fix the gap?"],
            "capstone_action": "Prove notes in studio (private).",
            "done_when": "Course 15 acceptance met.",
        },
        142: {
            "one_liner": "Prove: offer letter or structured interview feedback (Course 15 closure).",
            "why_now": "Final prove row—capture outcome or learning from the search loop.",
            "mental_model": "Private notes in studio backup are OK; public repo stays synthetic.",
            "beginner_extra": "Link offer PDF or write 5 bullets of feedback themes in prove notes.",
            "intermediate_deep_dive": "Retro: which prove artifacts interviewers asked about most.",
            "advanced_extra": "Update positioning statement from real feedback (private doc).",
            "failure_modes": ["Skipping written debrief when no offer yet"],
            "interview_prompts": ["What would you change in the capstone story for the next loop?"],
            "capstone_action": "Studio prove URL or backup JSON notes.",
            "done_when": "Course 15 prove acceptance checklist complete.",
        },
    }
