"""Handbook entries orders 31–70 (Course 2 end – Course 7)."""

from __future__ import annotations

from typing import Any


def entries() -> dict[int, dict[str, Any]]:
    return {
        31: {
            "one_liner": "LangGraph official docs—graphs, checkpointers, interrupts, and streaming for your reconciler-agent package.",
            "why_now": "Reference while implementing Month 2 build; short course gives intuition, docs give API truth.",
            "mental_model": "Docs = contract for state transitions and persistence.",
            "beginner_extra": "Read Concepts + Persistence before copying StackOverflow snippets.",
            "intermediate_deep_dive": "Implement SQLite or Postgres checkpointer; document migration path to prod store.",
            "advanced_extra": "Plan horizontal scaling: single-writer checkpoints, idempotent nodes, saga compensation on tool failure.",
            "read_sections": ["Concepts", "Persistence", "Interrupts", "Streaming"],
            "failure_modes": ["Non-idempotent nodes on retry", "Storing secrets in graph state"],
            "interview_prompts": ["How do checkpoints interact with idempotency keys?"],
            "capstone_action": "Package `reconciler-agent` with documented checkpointer choice.",
            "done_when": "Graph resumes after simulated worker crash.",
        },
        32: {
            "one_liner": "Applied LLMs pass on agents/orchestration—align handbook patterns with your LangGraph design.",
            "why_now": "Third handbook pass; focus agent chapters now that graphs are real code.",
            "mental_model": "Crosswalk essay + handbook + your README diagram.",
            "beginner_extra": "Read agent/orchestration sections only; skip unrelated chapters.",
            "intermediate_deep_dive": "Update ADR with one handbook pattern you implemented vs deferred.",
            "advanced_extra": "Define SLAs for HITL steps and escalation when interrupts age out.",
            "read_sections": ["Agents", "Orchestration", "Human oversight"],
            "failure_modes": ["Documentation drift from actual graph"],
            "interview_prompts": ["Describe your HITL path end-to-end."],
            "capstone_action": "Sync README diagram with handbook terminology.",
            "done_when": "Diagram matches code entrypoints.",
        },
        33: {
            "one_liner": "Build reconciler-agent: LangGraph workflow with SQLite/Postgres checkpointer and validation branch.",
            "why_now": "Month 2 core integration—extraction graph replaces one-off scripts.",
            "mental_model": "Graph = orchestration layer; extraction module unchanged underneath.",
            "beginner_extra": "Smallest graph that calls existing `extract()` then validates.",
            "intermediate_deep_dive": "Nodes as pure functions; explicit state schema; tests with mocked LLM.",
            "advanced_extra": "Emit OpenTelemetry spans per node; propagate trace id into LiteLLM metadata.",
            "failure_modes": ["Business logic inside prompt-only", "No version on state schema"],
            "interview_prompts": ["Show how you tested a branching graph."],
            "capstone_action": "Merge package with README run instructions.",
            "done_when": "CI tests graph without network.",
        },
        34: {
            "one_liner": "Prove Month 2: README demo of validation fail → interrupt() → human fix → resume.",
            "why_now": "Shows operable human-in-the-loop—not a slide deck.",
            "mental_model": "GIF or numbered steps = acceptance test for agents.",
            "beginner_extra": "Record terminal or write step-by-step with expected prompts.",
            "intermediate_deep_dive": "Include run id, checkpoint id, and how operator edits state safely.",
            "advanced_extra": "Redact PII in demo data; document authorization for who may resume.",
            "failure_modes": ["Demo only works on your laptop magic env"],
            "interview_prompts": ["Walk through HITL demo in interview."],
            "capstone_action": "Publish demo section; link in Lab & Prove.",
            "done_when": "Reviewer can reproduce HITL flow.",
        },
        35: {
            "one_liner": "Daily Dose of DS MCP playlist—practical Model Context Protocol explainers and examples.",
            "why_now": "Month 3 introduces tools; MCP is how clients discover and call them safely.",
            "mental_model": "MCP = gRPC/REST catalog for agent tools with schemas.",
            "beginner_extra": "Watch MCP overview episodes before reading spec—build vocabulary.",
            "intermediate_deep_dive": "Note security themes: auth, scope, audit—map to your tool list.",
            "advanced_extra": "Compare MCP to bespoke REST tool adapters—when standardization wins.",
            "watch_for": ["Server vs client roles", "Tool schemas", "Transport options"],
            "failure_modes": ["Exposing admin tools without auth"],
            "interview_prompts": ["How is MCP different from arbitrary HTTP tools?"],
            "capstone_action": "List planned tools with risk tier in README.",
            "done_when": "You can draw client ↔ MCP server ↔ tool diagram.",
        },
        36: {
            "one_liner": "Multi-agent MCP + FastAPI video—wiring agents to MCP servers in a service architecture.",
            "why_now": "Shows how your future MCP server sits beside the reconciler API.",
            "mental_model": "FastAPI = edge; MCP = tool plane.",
            "beginner_extra": "Focus on process boundaries, not copying entire repo.",
            "intermediate_deep_dive": "Sketch deploy diagram: agent, MCP server, DB, gateway.",
            "advanced_extra": "mTLS or token auth between agent and MCP; rate limits per tool.",
            "watch_for": ["Service layout", "Tool registration", "Error propagation"],
            "failure_modes": ["Monolith mixing UI, agent, and tools in one process"],
            "interview_prompts": ["Where would you put auth for tool calls?"],
            "capstone_action": "Update architecture diagram with MCP service box.",
            "done_when": "Diagram shows network boundaries.",
        },
        37: {
            "one_liner": "Multi-agent MCP + HITL architecture—human gates when tool or model output is unsafe.",
            "why_now": "Combines Month 2 interrupts with Month 3 tools—realistic enterprise shape.",
            "mental_model": "HITL on tool args before execution for write-class tools.",
            "beginner_extra": "Watch for approval UX patterns—not just diagrams.",
            "intermediate_deep_dive": "Define which tools require human approval vs auto-run.",
            "advanced_extra": "Audit log ties user id to approved arg hash; replay protection.",
            "watch_for": ["Approval queues", "Role separation", "Audit trails"],
            "failure_modes": ["HITL only on final answer, not tool calls"],
            "interview_prompts": ["Design approval for a write tool."],
            "capstone_action": "Policy table: tool → auto / HITL / banned.",
            "done_when": "Table reviewed and committed.",
        },
        38: {
            "one_liner": "Optional CampusX LangGraph/MCP playlist episode—extra walkthrough if Month 3 feels abstract.",
            "why_now": "Optional reinforcement only.",
            "mental_model": "Supplement, not substitute for spec + build.",
            "beginner_extra": "One episode max unless blocked.",
            "intermediate_deep_dive": "If used, note one trick that saved time in MCP server code.",
            "advanced_extra": "Prefer primary MCP spec for security decisions.",
            "watch_for": ["MCP server setup"],
            "failure_modes": ["Playlist replaces prove gate"],
            "interview_prompts": ["How do you validate optional resources helped?"],
            "capstone_action": "Optional DEVLOG entry.",
            "done_when": "Skip allowed if MCP build progressing.",
        },
        39: {
            "one_liner": "MCP introduction—roles of hosts, clients, servers, tools, resources, and prompts.",
            "why_now": "Foundation doc before you implement FastMCP server.",
            "mental_model": "MCP standardizes tool discovery like OpenAPI for agents.",
            "beginner_extra": "Read introduction + tools chapters; draw your server on paper.",
            "intermediate_deep_dive": "Map each planned capstone tool to MCP tool schema with JSON Schema types.",
            "advanced_extra": "Threat model: tool poisoning, confused deputy, credential forwarding.",
            "read_sections": ["Introduction", "Tools", "Resources", "Security"],
            "failure_modes": ["Tools without input validation"],
            "interview_prompts": ["Explain MCP components in one diagram."],
            "capstone_action": "Draft tool schemas in repo before coding.",
            "done_when": "Schemas reviewed for least privilege.",
        },
        40: {
            "one_liner": "MCP specification/docs—normative details for transports, capabilities, and versioning.",
            "why_now": "When intro is clear, spec resolves arguments about behavior.",
            "mental_model": "Spec = RFC; implementations may differ—test yours.",
            "beginner_extra": "Skim TOC; deep-read sections matching your transport (stdio vs HTTP).",
            "intermediate_deep_dive": "Document which spec version you target; pin SDK versions accordingly.",
            "advanced_extra": "Plan version negotiation and backward-compatible tool schema changes.",
            "read_sections": ["Transports", "Lifecycle", "Tool definitions"],
            "failure_modes": ["Assuming Claude Desktop behavior equals your server"],
            "interview_prompts": ["How would you version a breaking tool schema change?"],
            "capstone_action": "SPEC_VERSION note in MCP server README.",
            "done_when": "Server declares capabilities explicitly.",
        },
        41: {
            "one_liner": "MCP Illustrated Guidebook—visual explanations complementing the spec.",
            "why_now": "Helps if spec language is dense; pair with hands-on FastMCP.",
            "mental_model": "Picture book for protocol flows.",
            "beginner_extra": "Use for sequence diagrams of tool calls.",
            "intermediate_deep_dive": "Redraw one diagram with your actual tool names.",
            "advanced_extra": "Use diagrams in onboarding doc for teammates.",
            "read_sections": ["Tool call flow", "Server setup"],
            "failure_modes": ["Illustrations without matching implementation"],
            "interview_prompts": ["Whiteboard an MCP tool call sequence."],
            "capstone_action": "Add sequence diagram to docs/",
            "done_when": "Diagram matches implemented server.",
        },
        42: {
            "one_liner": "FastMCP—Pythonic MCP server framework to ship tools quickly with type hints.",
            "why_now": "Implementation path for Month 3 build milestone.",
            "mental_model": "FastMCP = FastAPI ergonomics for MCP tools.",
            "beginner_extra": "Start from template; one tool end-to-end before adding many.",
            "intermediate_deep_dive": "Structure repo: `mcp_server/` package, tests, docker-compose optional.",
            "advanced_extra": "Separate read-only vs write tools into different servers or policies.",
            "read_sections": ["Quickstart", "Tools", "Testing"],
            "failure_modes": ["God-object server with 20 tools day one"],
            "interview_prompts": ["How do you test MCP tools in CI?"],
            "capstone_action": "Scaffold FastMCP server with health check.",
            "done_when": "Local client can list tools.",
        },
        43: {
            "one_liner": "AI Engineering Hub roadmap MCP section—community patterns and example layouts.",
            "why_now": "Orientation for how others structure MCP repos—not gospel.",
            "mental_model": "Hub = Pinterest for repo layouts.",
            "beginner_extra": "Skim MCP section; steal folder naming only if it fits.",
            "intermediate_deep_dive": "Compare hub example to your audit/logging requirements.",
            "advanced_extra": "Document divergences from hub template with reasons.",
            "read_sections": ["MCP examples"],
            "failure_modes": ["Copy-paste without security review"],
            "interview_prompts": ["How do you evaluate third-party agent templates?"],
            "capstone_action": "README credits and divergence notes.",
            "done_when": "You know why your layout differs.",
        },
        44: {
            "one_liner": "JSON Schema—language-agnostic contracts for tool inputs/outputs and MCP tool definitions.",
            "why_now": "Shared vocabulary between MCP, OpenAPI later, and Pydantic models.",
            "mental_model": "JSON Schema = Avro/Protobuf for JSON documents.",
            "beginner_extra": "Read basics: types, required, enums, $ref.",
            "intermediate_deep_dive": "Generate or hand-write schemas for each tool; validate in tests.",
            "advanced_extra": "Schema registry in repo with compatibility checks on PR.",
            "read_sections": ["Understanding JSON Schema", "Reference"],
            "failure_modes": ["Loose `object` types everywhere"],
            "interview_prompts": ["How do JSON Schema and Pydantic relate?"],
            "capstone_action": "Commit schemas alongside tools.",
            "done_when": "Invalid args fail before tool executes.",
        },
        45: {
            "one_liner": "Build tools: lookup_schema, query_golden_set, run_readonly_query (allow-listed, safe).",
            "why_now": "First real MCP tools—read-only, auditable, least privilege.",
            "mental_model": "Tools = parameterized stored procedures with guardrails.",
            "beginner_extra": "Implement one tool completely before adding others.",
            "intermediate_deep_dive": "Enforce row limits, timeouts, and static allow-list of tables/collections.",
            "advanced_extra": "OPA policy preview for Month 9—block patterns in SQL strings.",
            "failure_modes": ["Arbitrary SQL tool", "No timeouts on DB calls"],
            "interview_prompts": ["Design a safe read-only warehouse tool."],
            "capstone_action": "Three tools with tests and schema.",
            "done_when": "Agent demo calls each tool successfully.",
        },
        46: {
            "one_liner": "Build audit fields on every tool call: user_id, tool, args_hash, timestamp.",
            "why_now": "Auditability is the prove differentiator for MCP month.",
            "mental_model": "Audit log = fact table for agent actions (like query audit in warehouses).",
            "beginner_extra": "Append-only JSON lines or DB table—pick one, document retention.",
            "intermediate_deep_dive": "Hash args after redacting secrets; never store raw API keys.",
            "advanced_extra": "Ship sample SIEM query or SQL to detect anomalous tool volume.",
            "failure_modes": ["Logging full payloads with PII", "Mutable audit tables"],
            "interview_prompts": ["What would you log for compliance on agent tools?"],
            "capstone_action": "Audit logger integrated; sample redacted line in README.",
            "done_when": "Every tool call produces one audit row.",
        },
        47: {
            "one_liner": "Prove Month 3: README plus redacted MCP client snippet showing tool call + audit line.",
            "why_now": "Evidence that MCP is integrated, not theoretical.",
            "mental_model": "Snippet = integration test narrative for reviewers.",
            "beginner_extra": "Redact tokens and PII; use synthetic data.",
            "intermediate_deep_dive": "Include steps: start server, list tools, invoke, show audit entry.",
            "advanced_extra": "Optional: short screen recording link.",
            "failure_modes": ["Secrets in snippet", "Audit not shown"],
            "interview_prompts": ["Demo MCP in 3 minutes."],
            "capstone_action": "Publish prove section; studio link.",
            "done_when": "Course 3 acceptance met.",
        },
        48: {
            "one_liner": "Document Chat RAG walkthrough—end-to-end retrieval augmented generation on a doc corpus.",
            "why_now": "Month 4 introduces search-before-generate for your reconciler knowledge base.",
            "mental_model": "RAG = join docs to question, then ask model with context.",
            "beginner_extra": "Watch once; note chunking, embedding, retrieval, generation order.",
            "intermediate_deep_dive": "Reproduce pipeline stages on your public corpus with named metrics.",
            "advanced_extra": "Compare video stack to your Qdrant/pgvector choice with ADR.",
            "watch_for": ["Chunking", "Embedding model", "Retrieval k", "Answer grounding"],
            "failure_modes": ["Skipping retrieval quality measurement"],
            "interview_prompts": ["Where does RAG fail even with good models?"],
            "capstone_action": "Pipeline diagram in README for Month 4.",
            "done_when": "You can name each stage’s inputs/outputs.",
        },
        49: {
            "one_liner": "Optional CampusX Advanced RAG outline—hybrid retrieval modules if dense search stalls.",
            "why_now": "Optional when recall@k is low on keyword-heavy queries.",
            "mental_model": "Hybrid = BM25 + vectors like SQL + search index.",
            "beginner_extra": "Only if benchmark table shows dense-only weakness.",
            "intermediate_deep_dive": "Complete hybrid module; rerun benchmark subset.",
            "advanced_extra": "Document when hybrid added cost without recall gain—honest negative results.",
            "watch_for": ["BM25 + dense fusion", "Reranking"],
            "failure_modes": ["Adding hybrid before baseline dense metrics"],
            "interview_prompts": ["When is hybrid search worth operational complexity?"],
            "capstone_action": "Optional benchmark appendix.",
            "done_when": "Decision recorded with numbers.",
        },
        50: {
            "one_liner": "Qdrant docs—vector database operations, filtering, and hybrid queries for RAG.",
            "why_now": "Primary retrieval store option for capstone benchmarks.",
            "mental_model": "Qdrant = specialized index for embeddings + metadata filters.",
            "beginner_extra": "Follow quickstart locally with docker.",
            "intermediate_deep_dive": "Define collection schema mirroring chunk metadata from Month 5.",
            "advanced_extra": "Capacity plan: vector size, HNSW params, replication for prod sketch.",
            "read_sections": ["Quickstart", "Filtering", "Hybrid queries"],
            "failure_modes": ["No metadata filters on tenant/doc_id"],
            "interview_prompts": ["Why Qdrant vs pgvector for your use case?"],
            "capstone_action": "Index sample chunks; query script in repo.",
            "done_when": "Script returns top-k with scores logged.",
        },
        51: {
            "one_liner": "Qdrant hybrid queries—combine dense vectors with sparse signals for better recall.",
            "why_now": "Implements optional hybrid strategy from syllabus benchmark.",
            "mental_model": "Hybrid query = weighted union of retrieval signals.",
            "beginner_extra": "Read after dense baseline works.",
            "intermediate_deep_dive": "Tune weights on labeled question set; document in benchmark table.",
            "advanced_extra": "Monitor query latency vs recall tradeoff; set SLO per query class.",
            "read_sections": ["Hybrid queries", "Sparse vectors"],
            "failure_modes": ["Default weights without evaluation"],
            "interview_prompts": ["Explain fusion strategies at high level."],
            "capstone_action": "Hybrid column in benchmark README table.",
            "done_when": "Table shows dense vs hybrid on same questions.",
        },
        52: {
            "one_liner": "pgvector—Postgres extension for embeddings when you want OLTP + vectors together.",
            "why_now": "Alternative retrieval store—familiar ops for data engineers.",
            "mental_model": "pgvector = one database for metadata and vectors.",
            "beginner_extra": "Spike if you already run Postgres for app state.",
            "intermediate_deep_dive": "Compare recall/latency vs Qdrant on same chunks—honest ADR.",
            "advanced_extra": "Index maintenance, vacuum, and memory tuning notes for interviews.",
            "read_sections": ["Installation", "Indexing", "Querying"],
            "failure_modes": ["Full table scan at scale without index"],
            "interview_prompts": ["When is pgvector enough vs dedicated vector DB?"],
            "capstone_action": "Optional second store benchmark or ADR why not.",
            "done_when": "Storage choice documented with metrics.",
        },
        53: {
            "one_liner": "Applied LLMs retrieval chapters—production RAG pitfalls and architecture patterns.",
            "why_now": "Fourth handbook pass focused on retrieval month.",
            "mental_model": "Handbook retrieval section = design review checklist.",
            "beginner_extra": "Read retrieval/RAG sections; skip unrelated chapters.",
            "intermediate_deep_dive": "Checklist: chunking, embedding model version, eval questions, injection defenses.",
            "advanced_extra": "Map handbook anti-patterns to tests in eval harness (Month 7).",
            "read_sections": ["Retrieval", "RAG", "Evaluation"],
            "failure_modes": ["Treating RAG as ‘add vector DB and done’"],
            "interview_prompts": ["Top three RAG production failures?"],
            "capstone_action": "RAG checklist in docs with tick marks.",
            "done_when": "Each item has owner file/test.",
        },
        54: {
            "one_liner": "Build public corpus for RAG—10-K sample, ops markdown, or synthetic docs with license clarity.",
            "why_now": "Retrieval quality is data quality—same as bronze layer curation.",
            "mental_model": "Corpus = source dataset with lineage and license metadata.",
            "beginner_extra": "Use only public/synthetic data; document provenance in README.",
            "intermediate_deep_dive": "Directory layout: raw/, normalized/, manifest.json with doc ids.",
            "advanced_extra": "Version corpus; evals pin corpus hash for reproducibility.",
            "failure_modes": ["Scraped content without license", "PII in corpus"],
            "interview_prompts": ["How do you version training/eval corpora?"],
            "capstone_action": "Commit corpus + manifest.",
            "done_when": "Manifest lists sources and dates.",
        },
        55: {
            "one_liner": "Build README benchmark: dense-only vs hybrid metrics on labeled questions.",
            "why_now": "Prove Month 4 with numbers—not vibes.",
            "mental_model": "Benchmark table = experiment results you would show in a design review.",
            "beginner_extra": "≥10 labeled questions with expected supporting doc ids.",
            "intermediate_deep_dive": "Metrics: recall@k, MRR, or human labeled hit rate—pick one, define it.",
            "advanced_extra": "Confidence intervals or note dataset size limitations honestly.",
            "failure_modes": ["Cherry-picked questions only"],
            "interview_prompts": ["Interpret a recall@5 regression."],
            "capstone_action": "Committed markdown table in README.",
            "done_when": "Table reproducible via script.",
        },
        56: {
            "one_liner": "Prove Month 4: committed benchmark table in repo.",
            "why_now": "Closes retrieval month with evidence.",
            "mental_model": "Prove = table + script command in README.",
            "beginner_extra": "Link in Lab & Prove.",
            "intermediate_deep_dive": "Reviewer reruns benchmark script and sees similar numbers.",
            "advanced_extra": "Attach failure cases where retrieval missed—shows maturity.",
            "failure_modes": ["Hand-edited metrics"],
            "interview_prompts": ["Discuss one retrieval failure from your table."],
            "capstone_action": "Publish prove link.",
            "done_when": "Course 4 acceptance satisfied.",
        },
        57: {
            "one_liner": "Docling (IBM)—document parsing pipeline for PDFs and office formats into structured content.",
            "why_now": "Month 5 chunking starts with high-quality parse, not naive text strip.",
            "mental_model": "Docling = ETL from documents to structured blocks.",
            "beginner_extra": "Run on one sample PDF; inspect output structure.",
            "intermediate_deep_dive": "Choose parse path for your corpus formats; document limitations.",
            "advanced_extra": "Batch parsing jobs with idempotent doc ids and error quarantine folder.",
            "watch_for": ["Layout preservation", "Table handling", "Export formats"],
            "failure_modes": ["Parser upgrades changing chunk hashes silently"],
            "interview_prompts": ["How do you regression-test document parsers?"],
            "capstone_action": "Parser script with sample input/output in repo.",
            "done_when": "One doc parses reproducibly.",
        },
        58: {
            "one_liner": "Docling documentation—configuration, models, and export options for production parsing.",
            "why_now": "Turns GitHub README spikes into repeatable pipeline config.",
            "mental_model": "Docs = operator guide for parse jobs.",
            "beginner_extra": "Read installation + usage for your OS/Sail equivalent.",
            "intermediate_deep_dive": "Pin model versions; log parser version in chunk metadata.",
            "advanced_extra": "SLA for parse failures; dead-letter queue for corrupt PDFs.",
            "read_sections": ["Installation", "Usage", "Export"],
            "failure_modes": ["Non-deterministic parses without version pins"],
            "interview_prompts": ["What metadata do you attach to each chunk?"],
            "capstone_action": "CONFIG.md for parser settings.",
            "done_when": "Chunks include parser_version field.",
        },
        59: {
            "one_liner": "LlamaParse getting started—managed parsing alternative/complement to Docling.",
            "why_now": "Compare build-vs-buy for parsing when Docling struggles on messy PDFs.",
            "mental_model": "LlamaParse = SaaS bronze loader for documents.",
            "beginner_extra": "Trial on one hard PDF; compare chunk quality to Docling.",
            "intermediate_deep_dive": "ADR: when to route to LlamaParse vs local Docling.",
            "advanced_extra": "Cost model per page; data residency and API key handling.",
            "watch_for": ["API workflow", "Output format", "Rate limits"],
            "failure_modes": ["Sending confidential docs to third party"],
            "interview_prompts": ["Build vs buy for document parsing?"],
            "capstone_action": "Comparison notes in docs/parsing.md.",
            "done_when": "Decision documented with example doc.",
        },
        60: {
            "one_liner": "Chip Huyen on data for LLM systems—how data quality drives RAG and eval outcomes.",
            "why_now": "Connects DE strengths to chunking and labeling work this month.",
            "mental_model": "Data card for corpus: schema, drift, ownership.",
            "beginner_extra": "Read one essay on data loops; list 3 data quality checks for chunks.",
            "intermediate_deep_dive": "Implement checks: empty chunks, duplicate hashes, missing page numbers.",
            "advanced_extra": "Lineage from raw doc → chunks.jsonl fields for Month 12 preview.",
            "read_sections": ["Data-centric LLM posts"],
            "failure_modes": ["Chunking without validation tests"],
            "interview_prompts": ["How is RAG data lineage different from warehouse lineage?"],
            "capstone_action": "Data quality tests on chunks.jsonl.",
            "done_when": "CI fails on bad chunk rows.",
        },
        61: {
            "one_liner": "Build chunks.jsonl with source_page, doc_id, chunk_id, and text fields.",
            "why_now": "Canonical retrieval input for Months 4–7 evals.",
            "mental_model": "chunks.jsonl = bronze table for semantic search.",
            "beginner_extra": "Schema in README; sample file committed.",
            "intermediate_deep_dive": "Stable chunking function with tests; idempotent rebuild from raw docs.",
            "advanced_extra": "Partition by doc_id; compaction job for orphaned chunks after reparse.",
            "failure_modes": ["Random chunk boundaries breaking tables", "No doc_id foreign key"],
            "interview_prompts": ["Design chunk schema for auditability."],
            "capstone_action": "Generate chunks.jsonl from corpus.",
            "done_when": "Schema validated in CI.",
        },
        62: {
            "one_liner": "Prove Month 5: sample chunks file plus documented schema in README.",
            "why_now": "Shows parsing/chunking pipeline exists.",
            "mental_model": "Prove = file + schema + generate command.",
            "beginner_extra": "Link in studio.",
            "intermediate_deep_dive": "Reviewer runs generate script and diffs sample hash optionally.",
            "advanced_extra": "Include row count and avg chunk length stats.",
            "failure_modes": ["Huge binary blobs in git—use LFS or samples"],
            "interview_prompts": ["Walk through chunk pipeline."],
            "capstone_action": "Publish prove artifacts.",
            "done_when": "Course 5 acceptance met.",
        },
        63: {
            "one_liner": "Neo4j GraphAcademy—graph fundamentals for relationship validation slice in Month 6.",
            "why_now": "Lightweight graph rules—not building Neo4j as primary store.",
            "mental_model": "Graph = constraint checker on entities extracted from corpus.",
            "beginner_extra": "Complete intro modules; learn nodes, relationships, Cypher basics.",
            "intermediate_deep_dive": "Model tiny graph matching your domain (doc, chunk, entity).",
            "advanced_extra": "When graph validation fails, surface human-readable explanation to agent.",
            "watch_for": ["Cypher MATCH patterns", "Constraints"],
            "failure_modes": ["Enterprise Neo4j ops scope creep"],
            "interview_prompts": ["Graph vs relational for validation rules?"],
            "capstone_action": "Graph schema diagram in docs.",
            "done_when": "You can write one MATCH query.",
        },
        64: {
            "one_liner": "Optional CampusX Graph RAG modules—only if pursuing GraphRAG beyond validator scope.",
            "why_now": "Optional; syllabus allows skip if validator prove passes.",
            "mental_model": "GraphRAG = advanced retrieval—not required for course prove.",
            "beginner_extra": "Skip unless interested; do not block Month 6 build.",
            "intermediate_deep_dive": "If taken, note one idea borrowed for validator messages.",
            "advanced_extra": "Separate experimental branch from main capstone.",
            "watch_for": ["Community detection", "Graph retrieval"],
            "failure_modes": ["Month-long GraphRAG detour"],
            "interview_prompts": ["When is GraphRAG overkill?"],
            "capstone_action": "Optional notes only.",
            "done_when": "Validator prove independent of this video.",
        },
        65: {
            "one_liner": "Microsoft GraphRAG repo—reference architecture for graph-based retrieval (read selectively).",
            "why_now": "Understand hype vs your scoped validator use case.",
            "mental_model": "GraphRAG pipeline = expensive; you borrow ideas, not whole stack.",
            "beginner_extra": "Read README architecture diagram only unless opting into frontier work.",
            "intermediate_deep_dive": "List components you are NOT building and why.",
            "advanced_extra": "If experimenting, measure cost vs flat RAG on same question set.",
            "read_sections": ["README", "Indexing pipeline overview"],
            "failure_modes": ["Adopting GraphRAG without eval uplift proof"],
            "interview_prompts": ["Contrast GraphRAG with your validator graph."],
            "capstone_action": "SCOPE.md boundaries for Month 6.",
            "done_when": "Scope doc committed.",
        },
        66: {
            "one_liner": "Neo4j Cypher manual—query language for validation rules and test fixtures.",
            "why_now": "Write rules that reject invalid entity relationships in CI.",
            "mental_model": "Cypher tests = dbt tests on a graph projection.",
            "beginner_extra": "Focus on MATCH/WHERE/RETURN patterns used in your tests.",
            "intermediate_deep_dive": "Parameterize queries; avoid injection via user-provided strings.",
            "advanced_extra": "Version graph projections; rebuild from chunks when upstream changes.",
            "read_sections": ["MATCH", "WHERE", "Constraints"],
            "failure_modes": ["Embedding Cypher as string concatenation from LLM output"],
            "interview_prompts": ["Write a Cypher rule for a business invariant."],
            "capstone_action": "cypher/ folder with rule queries.",
            "done_when": "Tests execute rules against sample graph.",
        },
        67: {
            "one_liner": "Build lightweight graph from Month 5 corpus; validator rejects invalid relationships.",
            "why_now": "Month 6 integration—quality gate before answers propagate.",
            "mental_model": "Validator = constraint job after extraction/retrieval.",
            "beginner_extra": "Smallest graph: entities you already extract + one relationship type.",
            "intermediate_deep_dive": "Fail closed: invalid graph → agent error path with explanation.",
            "advanced_extra": "Metrics: validation_failure_rate by rule id.",
            "failure_modes": ["Validator only logs warnings", "Graph stale vs chunks"],
            "interview_prompts": ["Where in pipeline does graph validation run?"],
            "capstone_action": "Validator module + sample failing case.",
            "done_when": "CI test expects failure on bad relationship.",
        },
        68: {
            "one_liner": "Prove Month 6: test case demonstrating validation failure on bad graph data.",
            "why_now": "Shows guardrail works—not only happy path.",
            "mental_model": "Negative test = prove for safety systems.",
            "beginner_extra": "Commit test + expected error message.",
            "intermediate_deep_dive": "Document operator steps when validation fails in agent flow.",
            "advanced_extra": "Link failure to HITL resume from Month 2.",
            "failure_modes": ["Only positive tests"],
            "interview_prompts": ["Demo a validation failure."],
            "capstone_action": "Prove link with test name cited.",
            "done_when": "Course 6 acceptance met.",
        },
        69: {
            "one_liner": "RAG evaluation video (Ragas context)—how to measure retrieval and generation quality.",
            "why_now": "Month 7 begins systematic eval harness beyond schema pass rate.",
            "mental_model": "RAG eval = join retrieval metrics + answer faithfulness metrics.",
            "beginner_extra": "Watch for metric definitions, not tool marketing.",
            "intermediate_deep_dive": "Pick 2 metrics you will implement in `evals/run`.",
            "advanced_extra": "Human eval for metrics that automation misjudges—sampled audit.",
            "watch_for": ["Faithfulness", "Context precision", "Pipeline diagram"],
            "failure_modes": ["Optimizing vanity metrics"],
            "interview_prompts": ["Which RAG metric would you gate CI on first?"],
            "capstone_action": "Metric selection doc before coding.",
            "done_when": "Two metrics named with thresholds.",
        },
        70: {
            "one_liner": "Optional CampusX RAGAS module—hands-on Ragas if video alone is insufficient.",
            "why_now": "Optional lab for Ragas APIs.",
            "mental_model": "Supplement to official Ragas docs.",
            "beginner_extra": "Take only if stuck implementing metrics.",
            "intermediate_deep_dive": "Complete one exercise; port to your golden set format.",
            "advanced_extra": "Prefer pinning ragas version in CI for reproducibility.",
            "watch_for": ["Dataset format", "Metric APIs"],
            "failure_modes": ["Course video replaces reading Ragas docs"],
            "interview_prompts": ["How do you debug a failing faithfulness score?"],
            "capstone_action": "Optional DEVLOG.",
            "done_when": "Skip if eval script already runs.",
        },
    }
